# PRISMA 2020 Keyword Lists
# Scope: English-language global digital market platforms
# Platforms: YouTube, Reddit, Bluesky, HackerNews
#
# IC-4: Text must contain >= 1 inclusion keyword
# EC-7: Text containing exclusion keywords is removed

INCLUSION_KEYWORDS = [

    # purchase behavior
    "buy",
    "buying",
    "bought",
    "purchase",
    "purchased",
    "purchasing",
    "order",
    "ordered",
    "ordering",
    "checkout",
    "add to cart",
    "wishlist",
    "impulse buy",
    "impulse purchase",
    "bulk buy",
    "repeat purchase",

    # product and review
    "product",
    "review",
    "reviewed",
    "rating",
    "rated",
    "star rating",
    "feedback",
    "recommend",
    "recommendation",
    "unboxing",
    "quality",
    "defective",
    "genuine",
    "authentic",
    "counterfeit",
    "fake product",
    "honest review",
    "verified purchase",
    "product description",
    "as described",
    "not as described",

    # shopping experience
    "shop",
    "shopping",
    "online store",
    "online shop",
    "online shopping",
    "store",
    "marketplace",
    "ecommerce",
    "e-commerce",
    "digital market",
    "digital marketplace",
    "digital commerce",
    "online commerce",
    "online retail",
    "retail",
    "platform",
    "seller",
    "vendor",
    "merchant",
    "third party seller",

    # global platforms
    "amazon",
    "ebay",
    "etsy",
    "walmart",
    "target",
    "best buy",
    "shopify",
    "woocommerce",
    "bigcommerce",
    "magento",
    "alibaba",
    "aliexpress",
    "temu",
    "shein",
    "wish",
    "overstock",
    "wayfair",
    "zappos",
    "newegg",
    "rakuten",

    # customer experience
    "customer",
    "consumer",
    "buyer",
    "client",
    "customer experience",
    "customer service",
    "customer support",
    "customer satisfaction",
    "customer review",
    "user experience",
    "after sales",
    "service quality",
    "support team",
    "live chat support",
    "help desk",
    "customer care",

    # complaints and issues
    "complaint",
    "issue",
    "problem",
    "refund",
    "return",
    "exchange",
    "warranty",
    "dispute",
    "chargeback",
    "damaged",
    "broken",
    "missing item",
    "wrong item",
    "lost package",
    "never arrived",
    "not delivered",
    "poor quality",

    # delivery and fulfillment
    "delivery",
    "delivered",
    "shipping",
    "shipped",
    "tracking",
    "package",
    "arrived",
    "late delivery",
    "delayed",
    "fast shipping",
    "free shipping",
    "courier",
    "logistics",
    "fulfillment",
    "dispatch",
    "express delivery",
    "standard shipping",
    "shipping cost",
    "delivery time",
    "estimated delivery",

    # price and deals
    "price",
    "pricing",
    "expensive",
    "cheap",
    "affordable",
    "discount",
    "deal",
    "sale",
    "offer",
    "promo",
    "promotion",
    "coupon",
    "voucher",
    "cashback",
    "rebate",
    "price drop",
    "best price",
    "overpriced",
    "value for money",
    "price comparison",
    "flash sale",
    "black friday",
    "cyber monday",
    "clearance",

    # sentiment and satisfaction signals
    "satisfied",
    "dissatisfied",
    "happy",
    "unhappy",
    "disappointed",
    "excellent",
    "terrible",
    "awful",
    "amazing",
    "fantastic",
    "horrible",
    "scam",
    "legit",
    "trusted",
    "trustworthy",
    "unreliable",
    "fraud",
    "misleading",
    "false advertising",
    "bait and switch",

    # purchase intent and decision signals
    "worth it",
    "not worth it",
    "would buy again",
    "will not buy",
    "highly recommend",
    "do not recommend",
    "best purchase",
    "worst purchase",
    "regret buying",
    "good deal",
    "bad deal",
    "wasted money",
    "money well spent",
    "totally worth",
    "not worth the price",
    "exceeded expectations",
    "below expectations",

    # consumer behavior and analytics
    "consumer behavior",
    "consumer behaviour",
    "buying behavior",
    "purchase behavior",
    "purchase intent",
    "buying intent",
    "shopping behavior",
    "consumer insight",
    "market research",
    "analytics",
    "trend",
    "preference",
    "engagement",
    "conversion",
    "conversion rate",
    "retention",
    "churn",
    "loyalty",
    "brand loyalty",
    "repeat customer",
    "customer lifetime value",
    "customer journey",
    "touchpoint",
    "funnel",
    "purchase funnel",

    # digital market and technology context
    "social commerce",
    "live shopping",
    "live stream shopping",
    "influencer marketing",
    "affiliate marketing",
    "sponsored review",
    "paid promotion",
    "organic review",
    "user generated content",
    "ugc",
    "product listing",
    "search ranking",
    "algorithm",
    "recommendation engine",
    "personalization",
    "targeted advertising",
    "retargeting",
    "abandoned cart",
    "cart abandonment",

    # trust and security
    "secure payment",
    "payment method",
    "credit card",
    "paypal",
    "data privacy",
    "personal data",
    "privacy policy",
    "terms of service",
    "account security",
    "identity theft",
    "phishing",
    "secure checkout",
    "ssl",
    "buyer protection",
    "money back guarantee",
    "return policy",
    "refund policy"
]


EXCLUSION_KEYWORDS = [
    # explicit content
    "porn",
    "xxx",
    "adult content",
    "nsfw",
    "nude",
    "naked",
    "onlyfans",
    "escort",
    "adult site",

    # financial fraud and spam
    "crypto scam",
    "investment fraud",
    "ponzi scheme",
    "get rich quick",
    "click here to win",
    "free money",
    "make money fast",
    "binary options",
    "forex scam",
    "pump and dump",

    # illegal content
    "illegal drug",
    "buy drugs online",
    "dark web",
    "stolen goods",
    "counterfeit money",

    # spam patterns
    "click here now",
    "limited time offer act now",
    "you have been selected",
    "congratulations you won",
    "claim your prize",
    "work from home scam",
    "mlm scheme",
    "pyramid scheme"
]